name: "3. Release"

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Modo Dry-Run (não publica)'
        type: boolean
        default: false
      strict-mode:
        description: 'Validar Conventional Commits rigorosamente'
        type: boolean
        default: true

  push:
    branches:
      - main

jobs:
  app:
    uses: heliomarpm/reusable-workflows/.github/workflows/cd-semantic-release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
    with:
      project-path: 'app'
      semantic-release-dry-run: ${{ inputs.dry-run || false }}
      strict-conventional-commits: ${{ inputs.strict-mode != false }}
      skip-version-file: true
    #   release_strategy: "release-branch"
    #   semantic_release_debug_mode: true
    #   semantic_release_dry_run: false
    #   strict_conventional_commits: false
